In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#df=pd.read_csv("./rhc.csv",index_col=0)
df=pd.read_csv("./propensity.csv")

In [ ]:
#心筋梗塞のデータ
#30日の死亡率

In [5]:
df

     age  male  risk  severity  trt  death
0     48     1     3         8    0      0
1     59     1     4         6    1      0
2     67     1     3         6    0      1
3     51     1     0         6    0      0
4     56     1     1         6    1      0
5     60     1     1         6    0      0
6     53     1     0         3    1      0
7     54     1     1         2    0      0
8     54     1     2         7    0      0
9     62     1     0         4    0      0
10    64     1     2         6    1      1
11    70     1     3         8    1      0
12    51     1     1         5    1      0
13    59     1     0         3    1      0
14    63     1     2         4    0      0
15    46     1     0         5    0      0
16    67     1     0         6    0      0
17    69     1     3         3    1      0
18    57     1     1         5    1      0
19    58     1     3         6    0      0
20    61     1     2         9    1      0
21    50     1     0         2    1      0
22    55     1     4         4    0      1
23    54     1     3         2    0      0
24    44     1     1         4    1      0
25    53     1     0         2    0      0
26    43     1     0         1    1      0
27    68     1     3         4    0      0
28    67     1     4         7    1      0
29    41     1     0         8    0      1
..   ...   ...   ...       ...  ...    ...
370   52     1     1         9    0      1
371   51     1     0         4    0      0
372   67     1     4         7    1      0
373   59     1     2         8    0      0
374   55     1     4         9    0      0
375   45     1     1         5    1      1
376   68     1     1         6    1      1
377   56     1     1         2    0      0
378   64     1     5         5    0      1
379   48     1     1         4    0      0
380   62     1     0         4    0      0
381   60     1     2         2    1      0
382   41     1     0         5    0      0
383   48     1     0         5    1      0
384   55     1     2         5    0      1
385   67     1     2         6    0      0
386   51     1     1         5    0      0
387   53     1     1         2    0      0
388   47     1     1         4    1      0
389   67     1     1         5    1      0
390   47     1     2         2    0      0
391   46     1     0         6    1      0
392   58     1     4         6    1      1
393   63     1     0         2    1      0
394   41     1     0         8    1      0
395   52     1     1         8    0      0
396   64     1     4         8    1      1
397   65     1     1         5    1      0
398   42     1     0         5    1      0
399   64     1     0         5    0      0

[400 rows x 6 columns]

In [6]:
#死亡者の比率
pd.crosstab(df.death,df.trt)

trt      0    1
death
0      168  162
1       40   30

標準療法が19%、血栓破壊薬を使用した場合が16%

In [30]:
X.shape

(400, 4)

In [43]:
df

     age  male  risk  severity  trt  death
0     48     1     3         8    0      0
1     59     1     4         6    1      0
2     67     1     3         6    0      1
3     51     1     0         6    0      0
4     56     1     1         6    1      0
5     60     1     1         6    0      0
6     53     1     0         3    1      0
7     54     1     1         2    0      0
8     54     1     2         7    0      0
9     62     1     0         4    0      0
10    64     1     2         6    1      1
11    70     1     3         8    1      0
12    51     1     1         5    1      0
13    59     1     0         3    1      0
14    63     1     2         4    0      0
15    46     1     0         5    0      0
16    67     1     0         6    0      0
17    69     1     3         3    1      0
18    57     1     1         5    1      0
19    58     1     3         6    0      0
20    61     1     2         9    1      0
21    50     1     0         2    1      0
22    55     1     4         4    0      1
23    54     1     3         2    0      0
24    44     1     1         4    1      0
25    53     1     0         2    0      0
26    43     1     0         1    1      0
27    68     1     3         4    0      0
28    67     1     4         7    1      0
29    41     1     0         8    0      1
..   ...   ...   ...       ...  ...    ...
370   52     1     1         9    0      1
371   51     1     0         4    0      0
372   67     1     4         7    1      0
373   59     1     2         8    0      0
374   55     1     4         9    0      0
375   45     1     1         5    1      1
376   68     1     1         6    1      1
377   56     1     1         2    0      0
378   64     1     5         5    0      1
379   48     1     1         4    0      0
380   62     1     0         4    0      0
381   60     1     2         2    1      0
382   41     1     0         5    0      0
383   48     1     0         5    1      0
384   55     1     2         5    0      1
385   67     1     2         6    0      0
386   51     1     1         5    0      0
387   53     1     1         2    0      0
388   47     1     1         4    1      0
389   67     1     1         5    1      0
390   47     1     2         2    0      0
391   46     1     0         6    1      0
392   58     1     4         6    1      1
393   63     1     0         2    1      0
394   41     1     0         8    1      0
395   52     1     1         8    0      0
396   64     1     4         8    1      1
397   65     1     1         5    1      0
398   42     1     0         5    1      0
399   64     1     0         5    0      0

[400 rows x 6 columns]

In [71]:
#df = df.iloc[:,1:]
#この変数選択が実は難しいのでは？DAGとか使わないと・・・
X = df.drop(['death','trt','male'],axis=1)
#dummycolumns=["age","risk","severity"]
#for i in dummycolumns:
#    dummy_X = pd.get_dummies(X[i],drop_first=True,prefix="{}_".format(i))
#    X = pd.concat([X, dummy_X],axis=1)
#X = X.drop(dummycolumns,axis=1)

In [72]:
X.shape

(400, 3)

In [75]:
#ロジスティック回帰
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X, df["trt"])
p_score=lr.predict_proba(X)
p_score=p_score[:,1]

In [77]:
lr.coef_

array([[0.01129087, 0.23230644, 0.11489375]])

In [78]:
import statsmodels.api as sm
lr = sm.Logit(df["trt"], X)
result = lr.fit()
ps=result.predict(X)

Optimization terminated successfully.
         Current function value: 0.665417
         Iterations 4

In [ ]:
df[""]

In [84]:
#層別マッチング(0.05刻み)
interval = np.arange(0,1.05,0.05)
match_list = []
table=df[["trt","death"]]
table["ps"]=ps
for i in range(0,len(interval)-1):
    temp0 = table[(table['trt']==0) & (interval[i] < table['ps']) & (table['ps'] < interval[i+1])]
    temp1 = table[(table['trt']==1) & (interval[i] < table['ps']) & (table['ps'] < interval[i+1])]
    if (len(temp0) > 0) & (len(temp1) > 0):
        match_list.append(temp1['death'].mean()-temp0['death'].mean())

np.mean(match_list)

/home/mizutani/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

-0.07617957949070803

In [76]:
#death ダミー変数化
#y = df1['death']
#dummy_y = pd.get_dummies(y)
#y = dummy_y['Yes']

#ps = pd.Series(result.predict(X))
#z1 = ps_target

#重み付け推定法
#ps = pd.Series(result.predict(X))
#z1 = ps_target
ps=p_score
z1=df["trt"]
y=df["death"]

ipwe1 = sum((z1*y)/ps)/sum(z1/ps)
ipwe0 = sum(((1-z1)*y)/(1-ps))/sum((1-z1)/(1-ps))
ipwe1 - ipwe0

-0.06299424826517289

In [22]:
import statsmodels.api as sm
#傾向スコアを求める
glm = sm.Logit(ps_target, X)
result = glm.fit()
ps = pd.Series(result.predict(X))

/home/mizutani/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

Optimization terminated successfully.
         Current function value: inf
         Iterations 6

/home/mizutani/anaconda3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py:1214: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
/home/mizutani/anaconda3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py:1264: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))

In [27]:
result.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                            Results: Logit
=======================================================================
Model:                 Logit             No. Iterations:    6.0000
Dependent Variable:    RHC               Pseudo R-squared:  -inf
Date:                  2018-10-29 16:37  AIC:               inf
No. Observations:      5735              BIC:               inf
Df Model:              11                Log-Likelihood:    -inf
Df Residuals:          5723              LL-Null:           -4.4225e+05
Converged:             1.0000            Scale:             1.0000
-----------------------------------------------------------------------
                        Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
-----------------------------------------------------------------------
age                    -0.0081   0.0014  -5.9659 0.0000 -0.0108 -0.0055
meanbp1                -0.0100   0.0007 -14.2463 0.0000 -0.0114 -0.0086
aps1                    0.0131   0.0013   9.8978 0.0000  0.0105  0.0156
cat1_CHF                0.5612   0.1066   5.2639 0.0000  0.3522  0.7702
cat1_COPD              -1.2461   0.1495  -8.3364 0.0000 -1.5391 -0.9531
cat1_Cirrhosis         -0.8648   0.1704  -5.0756 0.0000 -1.1988 -0.5309
cat1_Colon Cancer      -1.2290   1.1032  -1.1140 0.2653 -3.3913  0.9333
cat1_Coma              -0.5835   0.1288  -4.5312 0.0000 -0.8359 -0.3311
cat1_Lung Cancer       -1.1569   0.4867  -2.3771 0.0174 -2.1108 -0.2030
cat1_MOSF w/Malignancy -0.2263   0.1160  -1.9508 0.0511 -0.4537  0.0011
cat1_MOSF w/Sepsis      0.5909   0.0741   7.9703 0.0000  0.4456  0.7362
sex_Male                0.0901   0.0580   1.5550 0.1199 -0.0235  0.2037
=======================================================================

"""

In [28]:
#施術を受ける確率
ps

1       0.176820
2       0.494097
3       0.474606
4       0.368799
5       0.602842
6       0.069037
7       0.294091
8       0.228073
9       0.428026
10      0.377980
11      0.359747
12      0.422082
13      0.551773
14      0.548473
15      0.367481
16      0.227193
17      0.404167
18      0.389350
19      0.644851
20      0.472682
21      0.665132
22      0.280735
23      0.557296
24      0.213560
25      0.463706
26      0.237898
27      0.175015
28      0.453574
29      0.412905
30      0.498309
          ...
5706    0.192184
5707    0.104067
5708    0.564848
5709    0.499508
5710    0.499791
5711    0.629720
5712    0.405348
5713    0.557010
5714    0.368872
5715    0.620703
5716    0.093904
5717    0.366334
5718    0.224116
5719    0.411932
5720    0.741341
5721    0.450531
5722    0.319644
5723    0.590373
5724    0.516310
5725    0.326785
5726    0.567462
5727    0.353215
5728    0.694877
5729    0.574272
5730    0.191505
5731    0.513143
5732    0.456434
5733    0.156495
5734    0.176625
5735    0.382896
Length: 5735, dtype: float64

In [30]:
#death ダミー変数化
y = df1['death']
dummy_y = pd.get_dummies(y)
y = dummy_y['Yes']

ps = pd.Series(result.predict(X))
z1 = ps_target

#重み付け推定法
ps = pd.Series(result.predict(X))
z1 = ps_target
y = y
ipwe1 = sum((z1*y)/ps)/sum(z1/ps)
ipwe0 = sum(((1-z1)*y)/(1-ps))/sum((1-z1)/(1-ps))
ipwe1 - ipwe0

0.04393821268968601